### ISSUE TITLE
[BUG] Toggling dark mode causes unsaved changes to be lost.

### ISSUE THREAD

**Issue by dembeck** [bostrot/wsl2-distro-manager#82] opened 2023-02-02 01:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Toggling dark mode causes unsaved changes to be lost.

### Expected Behavior

Toggling dark mode should not discard changed but unsaved settings, or there should be a warning that toggling dark mode will cause unsaved changes to be lost.

### Steps To Reproduce

1. Go to Settings.
2. Change some settings.
3. Without saving, toggle dark mode.
4. All changed but unsaved settings are reset. 

### Environment

```markdown
- Windows Version: Windows 11 Enterprise 22621
- WSL Distro Manager Version: v1.5.0
- WSL Version:  ``` wsl --version ``` **does not work.**
- wsl --status
  - Default Distribution: v21.04-Ubuntu
  - Default Version: 2
  - Windows Subsystem for Linux was last updated on 2022-03-26
  - WSL automatic updates are on.
- Source: GitHub releases (for WSL Distro Manager)
```

**Comment by dembeck** [comment] 2023-02-02 19:34
@bostrot I just tried build 2023-02-02 [b851c3b](https://github.com/bostrot/wsl2-distro-manager/commit/b851c3b257c05f8c228637cfd79284a114890121) | `./build/windows/runner/Release/`

This seems almost fixed, it now keeps the unsaved settings **if** you set them while in dark mode, then toggle dark mode. But if you change a setting while in light mode, then toggle dark mode, the unsaved settings are lost.

**Comment by dembeck** [comment] 2023-02-02 20:05
#### Playing with it a bit more, these are some patterns I have noticed:

---

**Starting in Dark Mode**

- Changing a setting in dark mode, then toggling to light always keeps the setting.
- Changing a setting in dark mode, then toggling to light, then modify the unsaved setting in light mode, then toggle to dark then back to light, always causes the unsaved settings to be lost.

---

**Starting in Light Mode**

- Changing a setting in light mode, then toggling to dark usually loses the unsaved setting, but not always.
- Changing a setting in light mode, then toggling to dark to light to dark, the unsaved setting is always lost.

---


###### *When I say always, I mean always in the limited five minutes of testing that I did.

**Comment by bostrot** [comment] 2023-02-02 20:24
That is very strange behavior! And very specific :D 
Could you try the latest build from [this branch](https://github.com/bostrot/wsl2-distro-manager/tree/84-bug-maximizing-the-window-crashes-app/build/windows/runner/Release) if that fixes it? (in my testing it worked so I am not really sure what the issue could be right now)

**Comment by dembeck** [comment] 2023-02-02 22:55
Testing that build:

This build still always forgets the unsaved settings by the fourth light-dark-light cycle.
Whether the setting is originally set in dark or light mode does not seem to make any difference.

**Comment by dembeck** [comment] 2023-02-02 23:13
@bostrot Just a heads up, that latest build has a bug where just opening the settings panel causes `.wslconfig` to be recreated with `[wsl2]` as the first line, followed by two blank lines. It does this before clicking or changing any settings in the panel.

I think it is recreating vs erasing because as a test I saved a `.wslconfig` with ANSI encoding and CR LF line endings, and after opening settings the new file has UTF8 encoding with LF line endings and all settings removed.

The release version does not do this.

**Comment by dembeck** [comment] 2023-02-02 23:45
After using NirSoft's FileActivityWatch it is not actually deleting the `.wslconfig` file just saving over it.

**Comment by bostrot** [comment] 2023-02-03 07:48
> Testing that build:
> 
> This build still always forgets the unsaved settings by the fourth light-dark-light cycle. Whether the setting is originally set in dark or light mode does not seem to make any difference.

That is weird. This doesn't seem to happen with my testing. Also, I am not sure it is that relevant as it doesn't seem likely that someone just "spams" the dark mode/light mode button (please correct me if you have serious thoughts about this).

> @bostrot Just a heads up, that latest build has a bug where just opening the settings panel causes `.wslconfig` to be recreated with `[wsl2]` as the first line, followed by two blank lines. It does this before clicking or changing any settings in the panel.
> 
> I think it is recreating vs erasing because as a test I saved a `.wslconfig` with ANSI encoding and CR LF line endings, and after opening settings the new file has UTF8 encoding with LF line endings and all settings removed.
> 
> The release version does not do this.

This is happening because with the latest build it now saves every time the widget disposes (whereas it only saved before when you clicked on the save button). 

I agree that there should be some handling and taking into account if there are already settings in the `.wslconfig` file. I opened another issue for this (#87).

**Comment by bostrot** [comment] 2023-02-12 15:57
Btw I just saw that you are using a WSL version before v1.0.0 as `wsl --version` was introduced there. Make sure you upgrade.

Also, I am closing this for now as switching back and forth several times to reproduce this is not the intended behavior anyways.

**Closed by bostrot** 2023-02-12 15:57 UTC
Labels: bug, good first issue
