### ISSUE TITLE
Trojan Found in the file,

### ISSUE THREAD

**Issue by Karthikeyan020** [bostrot/wsl2-distro-manager#227] opened 2023-11-16 05:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There was a
![Screenshot 2023-11-16 134814](https://github.com/bostrot/wsl2-distro-manager/assets/34765552/3660e096-fa99-43d0-90ce-e4176a4e5880)
 trojan file found in the zip, i found this when i scanned using my linux system

### Expected Behavior

I deleted the file

### Steps To Reproduce

1. Just extract the file, system will detect the trojan

### Environment

```markdown
- Windows Version: Windows 11 version 21H2 (OS build 22000.2538)
- WSL Distro Manager Version: 1.18.1
- WSL Version: v2
- Source: Github release
```

### Anything else?

That's all

**Comment by bostrot** [comment] 2023-11-16 20:09
Are you sure that the file was not corrupted or something? I just scanned those with virustotal and it does not say anything (Windows does not complain either). Also you can check the source here: https://github.com/bitsdojo/bitsdojo_window

[VirusTotal desktop_window_plugin.dll](https://www.virustotal.com/gui/file/cf61b1c8d0e69f5f06e641873756053d70375f041c1f5b76efe2499d3e8d70c0)

**Comment by bostrot** [comment] 2023-11-25 11:13
Closing as I can't reproduce this. Reopen this if you feel the need to.

**Closed by bostrot** 2023-11-25 11:13 UTC
Labels: bug
